databases:
  - name: bloghehe
    databaseName: bloghehe
    user: bloghehe

services:
  - type: web
    name: bloghehe
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bloghehe
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
